# Site settings
title: Tu propio sitio personalizable
email: Kennetps@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Esta podria ser tu pagina, hechale un vistaso a como puedes tener tu informacion en un lugar confiable y ampliar tus contactos con una mejor aparienia
baseurl: "/-folio/" # the subpath of your site, e.g. /blog/  
url: "http://username.github.io" # the base hostname & protocol for your site
twitter_username: kennetps
github_username:  kennetps

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  poetry:
    output: true
    permalink: /poetry/:path/


